### ISSUE TITLE
Email Template

### ISSUE THREAD

**Issue by jp-samit** [samitsolutions/atgmanager#20]
Create nice simple e-mail template with SAM IT logo and a table that includes the locations that the user/admin has access to with a column that lists the status (either "OK" or "Needs Attention") and a column with a "View" hyperlink that will take them to the page listing the most recent data for that location.

**Comment by jp-samit** [comment]
- We should add a small margin at the top of the SAM IT logo, maybe 10px

- Change the logo to use the one from the samitsolutions.com website (black lettering for SAM and SOLUTIONS)

- Data is duplicated within the comments for Eagles #6 and there should be a percent sign in the "# full" section.  (Example: 'DIESEL 2 DISP. 7-8 is 14 full' should be 'DIESEL 2 DISP. 7-8 is 14% full')

- It says that Eagles #4 and Eagles #1 are OK, but we were unable to communicate with them at the time this e-mail was sent.

- The line that reads '*Values and statuses above are listed only for demonstrational.' should instead be '*Values and statuses above are listed only for demonstrational purposes.'

- The line that reads 'Never miss out on important informations related to your fuel tanks and locations' should instead be 'Never miss out on important information related to your fuel tanks and locations.'

- The table headers 'Location' and 'Status' should be bold

- Replace 'Hi!, Daily snapshot of your gas station activities.' with 'The following is a brief overview of the status of fuel tanks at the various stations you oversee.'

![uploads/cf70a923-5ec6-4be2-9149-0e6f03778709/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fcf70a923-5ec6-4be2-9149-0e6f03778709%2Fblob)

**Comment by codeyash** [comment]
Please provide black version logo

**Comment by jp-samit** [comment]
![uploads/dbf308bd-89e7-4780-90c2-223bd63720af/logo (2).png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fdbf308bd-89e7-4780-90c2-223bd63720af%2Flogo+%282%29.png)

**Comment by codeyash** [comment]
Fixed all points

**Comment by jp-samit** [comment]
There should be a percent sign in the "# full" section. (Example: 'DIESEL 2 DISP. 7-8 is 14 full' should be 'DIESEL 2 DISP. 7-8 is 14% full')
