### ISSUE TITLE
'Get Historical Data' Showing All Entries

### ISSUE THREAD

**Issue by jp-samit** [samitsolutions/atgmanager#29]
No matter what date is chosen in the date field, the analysis page shows all entries. Only entries matching the date chosen should be shown.

![uploads/925a863f-4f65-4dd0-b959-3a89ed987eb7/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F925a863f-4f65-4dd0-b959-3a89ed987eb7%2Fblob)

**Comment by codeyash** [comment]
Fixed
