### ISSUE TITLE
Change 'Calling App' text at top of 'Companies', 'Locations' and 'Scheduler' pages

### ISSUE THREAD

**Issue by jp-samit** [samitsolutions/atgmanager#6]
Page header should reflect what page the user/admin is on. Update 'Calling App' text to show this. If user/admin is on 'Companies' page, then it should say 'Companies'

Or remove the text completely, whichever one is better.

![uploads/3e6da5f2-5505-4721-9e8a-d79f1b173d09/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F3e6da5f2-5505-4721-9e8a-d79f1b173d09%2Fblob)

**Comment by codeyash** [comment]
There will be double for same words. So I can replace with ATG Manager.

Companies
Listing company

Won't look ok..right

So either blank or some other text would work.

Please suggest

**Comment by jp-samit** [comment]
ATG Manager is fine

**Comment by codeyash** [comment]
ok
